// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['Wailsapp']['Greet'](arg1);
}

export function Start() {
  return window['go']['main']['Wailsapp']['Start']();
}
